services:
  email-search-service:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-super-secret-jwt-key}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GOOGLE_SEARCH_ENGINE_ID=${GOOGLE_SEARCH_ENGINE_ID:-}
      - BING_API_KEY=${BING_API_KEY:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; requests.get('http://localhost:5001/api/email/health')\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

